### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/gentoo-rnp#1]

**Comment by ronaldtse** [comment]
@antonsviridenko can we proceed with it?

**Comment by antonsviridenko** [comment]
It is listed in Gentoo repositories list with 'master'
here
https://github.com/gentoo/api-gentoo-org/blob/master/files/overlays/repositories.xml#L3396

**Comment by ronaldtse** [comment]
Done. Now `main` and `master` are identical.

@antonsviridenko can you help make a PR to:

1. Change `<repo quality="experimental" status="unofficial">` to official
2. Change the branch name to main?
